---
language: node_js
node_js:
  - node
cache: yarn
script:
  - yarn run lerna:bootstrap
  - yarn run build
  - yarn run lint
  - yarn run test:coverage
after_success: yarn run coveralls
branches:
  only:
    - master
