---
language: node_js
node_js:
  - node
script:
  - npm run lerna -- bootstrap
  - npm run lint
  - npm run test:coverage
  - npm run build
after_success: npm run coveralls
branches:
  only:
    - master
